name: Deploy FastAPI to EKS

on:
  push:
    branches:
      - main

permissions:
  id-token: write        # REQUIRED for OIDC
  contents: read

env:
  AWS_REGION: ap-southeast-1
  EKS_CLUSTER_NAME: fastapi-cluster-v2
  ECR_REPOSITORY: fastapi-eks
  IMAGE_TAG: latest

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # üîê OIDC ‚Üí Assume IAM role
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::997868087240:role/github-eks-role
          aws-region: ${{ env.AWS_REGION }}

      # üîë Login to ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # üê≥ Build & Push image
      - name: Build and push Docker image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG \
            997868087240.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG
          docker push \
            997868087240.dkr.ecr.${AWS_REGION}.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

      # ‚ò∏Ô∏è Install kubectl
      - name: Install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
